[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
via_ir = true
optimizer = true
optimizer_runs = 200

[profile.optimized]
via_ir = true
optimizer = true
optimizer_runs = 1000
ir_optimized = true

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
